name: publish
on:
  push:
    branches:
      - master
jobs:
  publish-tiny-core-docker-image:
    name: Publish TinyCore Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/jbatch/tiny-core:latest
          docker push ghcr.io/jbatch/tiny-core:latest